# Generated by Django 6.0.7 on 2026-07-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_images/'),
        ),
    ]
